CREATE DATABASE frances;
USE frances;

<<<<<<< Updated upstream
CREATE TABLE USUARIOS (
	  ID_USUARIO INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador unico del usuario',
=======
--TABLA USUARIOS
CREATE TABLE usuarios (
	  ID INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador unico del usuario',
>>>>>>> Stashed changes
    EMAIL VARCHAR(100) NOT NULL COMMENT 'EMail del usuario',
    USERNAME VARCHAR(50) NOT NULL COMMENT 'Nombre de usuario',
    PASSWD CHAR(64) NOT NULL COMMENT 'Clave segura del usuario',
	  NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre del usuario',
    APELLIDOS VARCHAR(150) NOT NULL COMMENT 'Apellidos del usuario',
    TELEFONO CHAR(9) NOT NULL COMMENT 'Telefono movil del usuario',
    INSTITUTO VARCHAR(50) NULL COMMENT 'Instituto al que asiste el usuario'
	CONSTRAINT PK_ID PRIMARY KEY (ID)
);
<<<<<<< Updated upstream
CREATE TABLE GRUPO (
    ID_GRUPO INT(10) AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    CENTRO VARCHAR(64) NOT NULL,
    TUTOR INT(10) NOT NULL,
    CONSTRAINT FOREIGN KEY (TUTOR) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE ALUMNO_GRUPO (
    ID_USUARIO INT(10),
    ID_GRUPO INT(10),
    CONSTRAINT PRIMARY KEY (ID_USUARIO, ID_GRUPO),
    CONSTRAINT FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID_USUARIO),
    CONSTRAINT FOREIGN KEY (ID_USUARIO) REFERENCES Grupo(Id_Grupo)
);

CREATE TABLE CENTRO {
    ID_CENTRO INT(10) NOT NULL AUTO_INCREMENT COMMENT 'Identificador del centro',
    LOCALIDAD VARCHAR(50) NOT NULL COMMENT 'Localidad',
    PRIMARY KEY (ID_CENTRO, LOCALIDAD)
    FOREIGN KEY (ID_CENTRO) REFERENCES Centro(ID_CENTRO)
};
=======

-- TABLA ALUMNOS
CREATE TABLE alumnos (
    ID_USUARIO INT NOT NULL,
    NIVEL INT NOT NULL,
    RANGO CHAR(64) NOT NULL,
    ULTIMA_CONEXION DATETIME NULL,
    
    PRIMARY KEY (ID_USUARIO),
    
    CONSTRAINT FK_ALUMNO_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES usuarios(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- TABLA DOCENTES
CREATE TABLE docentes (
    ID_USUARIO INT NOT NULL,
    DIRECTOR BOOLEAN NOT NULL,
    
    PRIMARY KEY (ID_USUARIO),
    
    CONSTRAINT FK_DOCENTE_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES usuarios(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
>>>>>>> Stashed changes
